CMake:
  version: 2.8.5
  category: external_common
  path: Service

Mokka:
  version: 08-03
  category: cepcsoft
  path: Simulation

MySQL:
  category: system

LCIO:
  version: 02-04-03
  category: cepcsoft
  path: Framework

GEAR:
  version: 01-04
  category: cepcsoft
  path: Simulation

Geant4:
  version: 9.6.p02
  category: external_release
  path: Service

GSL:
  version: '1.14'
  category: external_common
  path: Service

ROOT:
  version: 5.34.10
  category: external_common
  path: Service

CLHEP:
  version: 2.1.3.1
  category: external_common
  path: Service
