release_version: 01-17-05

system:
  MySQL:
    version: >5.5

external-common:
  root:
    location: external-common
    path: Service
    version: 5.34.10

external-release:
  CLHEP:
    version: 5.34.10

cepcsoft:
  Mokka:
    path: Simulation
    version: mokka-08-03
    dep: [xxx, yyy, MySQL]

  KalTest:
    path: Reconstruction
    version: 02-00-32
    dep: [Marlin]
