Mokka:
  category: cepcsoft
  path: Simulation
  version: mokka-08-03
  dep: [ "LCIO", "GEAR", "Geant4", "MySQL" ]

MySQL:
  category: system

LCIO:
  category: cepcsoft
  path: Framework
  version: 02-04-03

GEAR:
  category: cepcsoft
  path: Simulation
  version: 01-04
  dep: CLHEP

Geant4:
  category: external_release
  path: Service
  version: 9.6.p02

ROOT:
  category: external_common
  path: Service
  version: 5.34.10

CLHEP:
  category: external_common
  path: Service
  version: 2.1.3.1
