external_path_default: &EXTERNAL_PATH_DEFAULT
  home: '{install_dir}'
  src: '{source_dir}'

cepcsoft_path_default: &CEPCSOFT_PATH_DEFAULT
  <<: *EXTERNAL_PATH_DEFAULT
  cmake: '{install_dir}'


external_default: &EXTERNAL_DEFAULT
  location:
    source: source
    build: build
    install: install

cepcsoft_default: &CEPCSOFT_DEFAULT
  location:
    source: ''
    build: build
    install: ''


gcc:
  <<: *EXTERNAL_DEFAULT
  basic: true
  path:
    <<: *EXTERNAL_PATH_DEFAULT
    bin: '{install_dir}/bin'
    lib: '{install_dir}/lib64'
    man: '{install_dir}/share/man'

CMake:
  <<: *EXTERNAL_DEFAULT
  basic: true
  dep: gcc
  path:
    <<: *EXTERNAL_PATH_DEFAULT
    bin: '{install_dir}/bin'
    lib: '{install_dir}/lib'
    man: '{install_dir}/man'


XercesC:
  <<: *EXTERNAL_DEFAULT
  path:
    <<: *EXTERNAL_PATH_DEFAULT
    bin: '{install_dir}/bin'
    inc: '{install_dir}/include'
    lib: '{install_dir}/lib'

GSL:
  <<: *EXTERNAL_DEFAULT
  path:
    <<: *EXTERNAL_PATH_DEFAULT
    bin: '{install_dir}/bin'
    inc: '{install_dir}/include'
    lib: '{install_dir}/lib'
    man: '{install_dir}/share/man'
    info: '{install_dir}/share/info'

QT:
  <<: *EXTERNAL_DEFAULT
  path:
    <<: *EXTERNAL_PATH_DEFAULT
    bin: '{install_dir}/bin'
    inc: '{install_dir}/include'
    lib: '{install_dir}/lib64'

CLHEP:
  <<: *EXTERNAL_DEFAULT
  path:
    <<: *EXTERNAL_PATH_DEFAULT
    bin: '{install_dir}/bin'
    inc: '{install_dir}/include'
    lib: '{install_dir}/lib'
    cmake: '{install_dir}'

Geant4:
  <<: *EXTERNAL_DEFAULT
  dep: [QT, CLHEP, XercesC]
  path:
    <<: *EXTERNAL_PATH_DEFAULT
    bin: '{install_dir}/bin'
    inc: '{install_dir}/include'
    lib: '{install_dir}/lib64'
    cmake: '{install_dir}'
  env:
    G4NEUTRONHPDATA: '{install_dir}/share/Geant4-9.6.2/data/G4NDL4.2'
    G4LEDATA: '{install_dir}/share/Geant4-9.6.2/data/G4EMLOW6.32'
    G4LEVELGAMMADATA: '{install_dir}/share/Geant4-9.6.2/data/PhotonEvaporation2.3'
    G4RADIOACTIVEDATA: '{install_dir}/share/Geant4-9.6.2/data/RadioactiveDecay3.6'
    G4NEUTRONXSDATA: '{install_dir}/share/Geant4-9.6.2/data/G4NEUTRONXS1.2'
    G4PIIDATA: '{install_dir}/share/Geant4-9.6.2/data/G4PII1.3'
    G4REALSURFACEDATA: '{install_dir}/share/Geant4-9.6.2/data/RealSurface1.0'
    G4SAIDXSDATA: '{install_dir}/share/Geant4-9.6.2/data/G4SAIDDATA1.1'

ROOT:
  <<: *EXTERNAL_DEFAULT
  path:
    <<: *EXTERNAL_PATH_DEFAULT
    bin: '{install_dir}/bin'
    inc: '{install_dir}/include'
    lib: '{install_dir}/lib'
    man: '{install_dir}/man'
  env:
    ROOTSYS: '{install_dir}'


ILCUTIL:
  <<: *CEPCSOFT_DEFAULT
  path:
    <<: *CEPCSOFT_PATH_DEFAULT
    lib: '{install_dir}/lib'

LCIO:
  <<: *CEPCSOFT_DEFAULT
  dep: [CLHEP, ROOT]
  path:
    <<: *CEPCSOFT_PATH_DEFAULT
    bin: '{install_dir}/bin'
    inc: '{install_dir}/include'
    lib: '{install_dir}/lib'
  env:
    LCIO: '{install_dir}'

GEAR:
  <<: *CEPCSOFT_DEFAULT
  dep: [ROOT, CLHEP, ILCUTIL]
  path:
    <<: *CEPCSOFT_PATH_DEFAULT
    bin: '{install_dir}/bin'
    inc: '{install_dir}/include'
    lib: '{install_dir}/lib'

Mokka:
  <<: *CEPCSOFT_DEFAULT
  dep: [LCIO, GEAR, Geant4, MySQL, ILCUTIL]
  path:
    <<: *CEPCSOFT_PATH_DEFAULT
    bin: '{install_dir}/bin'
    lib: '{install_dir}/lib'

Druid:
  <<: *CEPCSOFT_DEFAULT
  dep: [LCIO, GEAR, ROOT]
  path:
    home: '{install_dir}'
    src: '{source_dir}'
    bin: '{install_dir}/bin'

CED:
  <<: *CEPCSOFT_DEFAULT
  path:
    <<: *CEPCSOFT_PATH_DEFAULT
    bin: '{install_dir}/bin'
    inc: '{install_dir}/include'
    lib: '{install_dir}/lib'

CEDViewer:
  <<: *CEPCSOFT_DEFAULT
  dep: [Marlin, MarlinUtil, LCIO, GEAR, CLHEP, GSL, CED]
  path:
    <<: *CEPCSOFT_PATH_DEFAULT
    bin: '{install_dir}/bin'
    inc: '{install_dir}/include'
    lib: '{install_dir}/lib'


LCCD:
  <<: *CEPCSOFT_DEFAULT
  dep: LCIO
  path:
    <<: *CEPCSOFT_PATH_DEFAULT
    lib: '{install_dir}/lib'
    inc: '{install_dir}/include'
