common_location_default: &COMMON_LOCATION_DEFAULT
  source: source
  build: build
  install: install

ilcutil_location_default: &ILCUTIL_LOCATION_DEFAULT
  source: ''
  build: build
  install: ''


common_path_default: &COMMON_PATH_DEFAULT
  home: '{install}'
  src: '{source}'

cmake_path_default: &CMAKE_PATH_DEFAULT
  <<: *COMMON_PATH_DEFAULT
  cmake: '{install}'


GCC:
  basic: true
  location:
    <<: *COMMON_LOCATION_DEFAULT
  path:
    <<: *COMMON_PATH_DEFAULT
    bin: '{install}/bin'
    library: '{install}/lib64'
    man: '{install}/share/man'

CMake:
  basic: true
#  dep: GCC
  location:
    <<: *COMMON_LOCATION_DEFAULT
  path:
    <<: *COMMON_PATH_DEFAULT
    bin: '{install}/bin'
    library: '{install}/lib'
    man: '{install}/man'


XercesC:
  location:
    <<: *COMMON_LOCATION_DEFAULT
  path:
    <<: *CMAKE_PATH_DEFAULT
    bin: '{install}/bin'
    lib: '{install}/lib'
    library: '{install}/lib'
    inc: '{install}/include'

QT:
  location:
    <<: *COMMON_LOCATION_DEFAULT
  path:
    <<: *COMMON_PATH_DEFAULT
    bin: '{install}/bin'
    lib: '{install}/lib64'
    library: '{install}/lib64'
    inc: '{install}/include'

CLHEP:
  location:
    <<: *COMMON_LOCATION_DEFAULT
  path:
    <<: *CMAKE_PATH_DEFAULT
    bin: '{install}/bin'
    lib: '{install}/lib'
    library: '{install}/lib'
    inc: '{install}/include'

GSL:
  location:
    <<: *COMMON_LOCATION_DEFAULT
  path:
    <<: *COMMON_PATH_DEFAULT
    bin: '{install}/bin'
    lib: '{install}/lib'
    library: '{install}/lib'
    inc: '{install}/include'
    man: '{install}/share/man'
    info: '{install}/share/info'

ROOT:
  location:
    <<: *COMMON_LOCATION_DEFAULT
  path:
    <<: *COMMON_PATH_DEFAULT
    bin: '{install}/bin'
    lib: '{install}/lib'
    library: '{install}/lib'
    inc: '{install}/include'
    man: '{install}/man'
  env:
    ROOTSYS: '{install}'

Geant4:
  dep: [QT, CLHEP, XercesC]
  location:
    <<: *COMMON_LOCATION_DEFAULT
  path:
    <<: *CMAKE_PATH_DEFAULT
    bin: '{install}/bin'
    lib: '{install}/lib64'
    library: '{install}/lib64'
    inc: '{install}/include'
  env:
    G4INSTALL: '{install}'
    G4NEUTRONHPDATA: '{install}/share/Geant4-9.6.2/data/G4NDL4.2'
    G4LEDATA: '{install}/share/Geant4-9.6.2/data/G4EMLOW6.32'
    G4LEVELGAMMADATA: '{install}/share/Geant4-9.6.2/data/PhotonEvaporation2.3'
    G4RADIOACTIVEDATA: '{install}/share/Geant4-9.6.2/data/RadioactiveDecay3.6'
    G4NEUTRONXSDATA: '{install}/share/Geant4-9.6.2/data/G4NEUTRONXS1.2'
    G4PIIDATA: '{install}/share/Geant4-9.6.2/data/G4PII1.3'
    G4REALSURFACEDATA: '{install}/share/Geant4-9.6.2/data/RealSurface1.0'
    G4SAIDXSDATA: '{install}/share/Geant4-9.6.2/data/G4SAIDDATA1.1'


ILCUTIL:
  location:
    <<: *ILCUTIL_LOCATION_DEFAULT
  path:
    <<: *CMAKE_PATH_DEFAULT
    lib: '{install}/lib'
    library: '{install}/lib'
    inc: '{install}/include'

LCIO:
  dep: [CLHEP, ROOT, ILCUTIL]
  location:
    <<: *ILCUTIL_LOCATION_DEFAULT
  path:
    <<: *CMAKE_PATH_DEFAULT
    bin: '{install}/bin'
    lib: '{install}/lib'
    library: '{install}/lib'
    inc: '{install}/include'
  env:
    LCIO: '{install}'

GEAR:
  dep: [CLHEP, ROOT, ILCUTIL]
  location:
    <<: *ILCUTIL_LOCATION_DEFAULT
  path:
    <<: *CMAKE_PATH_DEFAULT
    bin: '{install}/bin'
    lib: '{install}/lib'
    library: '{install}/lib'
    inc: '{install}/include'

Mokka:
  dep: [Geant4, MySQL, ILCUTIL, LCIO, GEAR]
  location:
    <<: *ILCUTIL_LOCATION_DEFAULT
  path:
    <<: *CMAKE_PATH_DEFAULT
    bin: '{install}/bin'
    lib: '{install}/lib'

CondDBMySQL:
  dep: [MySQL, ILCUTIL]
  location:
    <<: *ILCUTIL_LOCATION_DEFAULT
  path:
    <<: *CMAKE_PATH_DEFAULT
    bin: '{install}/bin'
    lib: '{install}/lib'

Druid:
  dep: [LCIO, GEAR, ROOT]
  location:
    <<: *ILCUTIL_LOCATION_DEFAULT
  path:
    <<: *COMMON_PATH_DEFAULT
    bin: '{install}/bin'

CED:
  dep: [GLUT, OpenGL, ILCUTIL]
  location:
    <<: *ILCUTIL_LOCATION_DEFAULT
  path:
    <<: *CMAKE_PATH_DEFAULT
    bin: '{install}/bin'
    lib: '{install}/lib'
    inc: '{install}/include'

CEDViewer:
  dep: [CLHEP, GSL, ILCUTIL, LCIO, GEAR, Marlin, MarlinUtil, CED, LCCD]
  location:
    <<: *ILCUTIL_LOCATION_DEFAULT
  path:
    <<: *CMAKE_PATH_DEFAULT
    bin: '{install}/bin'
    lib: '{install}/lib'
    inc: '{install}/include'
    marlin: '{install}/lib/libCEDViewer.so'

FastJet:
  location:
    <<: *COMMON_LOCATION_DEFAULT
  path:
    <<: *CMAKE_PATH_DEFAULT
    bin: '{install}/bin'
    lib: '{install}/lib'
    library: '{install}/lib'
    inc: '{install}/include'

FastJetClustering:
  dep: [ROOT, ILCUTIL, Marlin, MarlinUtil, CLHEP, GEAR, GSL, LCIO, FastJet]
  location:
    <<: *ILCUTIL_LOCATION_DEFAULT
  path:
    <<: *CMAKE_PATH_DEFAULT
    lib: '{install}/lib'
    inc: '{install}/include'
    marlin: '{install}/lib/libFastJetClustering.so'

MarlinFastJet:
  dep: [ILCUTIL, LCIO, Marlin, FastJet, RAIDA]
  location:
    <<: *ILCUTIL_LOCATION_DEFAULT
  path:
    <<: *CMAKE_PATH_DEFAULT
    lib: '{install}/lib'
    inc: '{install}/include'
    marlin: '{install}/lib/libMarlinFastJet.so'

KalTest:
  dep: [ILCUTIL, ROOT]
  location:
    <<: *ILCUTIL_LOCATION_DEFAULT
  path:
    <<: *CMAKE_PATH_DEFAULT
    bin: '{install}/bin'
    lib: '{install}/lib'
    library: '{install}/lib'
    inc: '{install}/include'

KalDet:
  dep: [ROOT, ILCUTIL, LCIO, GEAR, KalTest, Marlin, MarlinUtil]
  location:
    <<: *ILCUTIL_LOCATION_DEFAULT
  path:
    <<: *CMAKE_PATH_DEFAULT
    lib: '{install}/lib'
    inc: '{install}/include'

GBL:
  dep: [ROOT, ILCUTIL]
  location:
    <<: *ILCUTIL_LOCATION_DEFAULT
  path:
    <<: *CMAKE_PATH_DEFAULT
    bin: '{install}/bin'
    lib: '{install}/lib'
    inc: '{install}/include'

LCCD:
  dep: [ILCUTIL, LCIO]
  location:
    <<: *ILCUTIL_LOCATION_DEFAULT
  path:
    <<: *CMAKE_PATH_DEFAULT
    lib: '{install}/lib'
    inc: '{install}/include'

RAIDA:
  dep: [ROOT, ILCUTIL]
  location:
    <<: *ILCUTIL_LOCATION_DEFAULT
  path:
    <<: *CMAKE_PATH_DEFAULT
    bin: '{install}/bin'
    lib: '{install}/lib'
    inc: '{install}/include'

MarlinUtil:
  dep: [CLHEP, GSL, ILCUTIL, GEAR, LCIO, Marlin, CED]
  location:
    <<: *ILCUTIL_LOCATION_DEFAULT
  path:
    <<: *CMAKE_PATH_DEFAULT
    lib: '{install}/lib'
    inc: '{install}/include'

Marlin:
  dep: [CLHEP, QT, ILCUTIL, LCIO, GEAR, LCCD, RAIDA]
  location:
    <<: *ILCUTIL_LOCATION_DEFAULT
  path:
    <<: *CMAKE_PATH_DEFAULT
    bin: '{install}/bin'
    lib: '{install}/lib'
    inc: '{install}/include'

MarlinReco:
  dep: [CLHEP, GSL, ROOT, ILCUTIL, Marlin, MarlinUtil, GEAR, LCIO, RAIDA]
  location:
    <<: *ILCUTIL_LOCATION_DEFAULT
  path:
    <<: *CMAKE_PATH_DEFAULT
    lib: '{install}/lib'
    marlin: '{install}/lib/libMarlinReco.so'

MarlinTrk:
  dep: [GSL, CLHEP, ROOT, ILCUTIL, LCIO, GEAR, Marlin, MarlinUtil, KalTest, KalDet, RAIDA]
  location:
    <<: *ILCUTIL_LOCATION_DEFAULT
  path:
    <<: *CMAKE_PATH_DEFAULT
    lib: '{install}/lib'
    inc: '{install}/include'

MarlinTrkProcessors:
  dep: [ROOT, GSL, ILCUTIL, LCIO, Marlin, MarlinUtil, KalTest, KalDet, MarlinTrk, KiTrack, KiTrackMarlin, RAIDA]
  location:
    <<: *ILCUTIL_LOCATION_DEFAULT
  path:
    <<: *CMAKE_PATH_DEFAULT
    lib: '{install}/lib'
    marlin: '{install}/lib/libMarlinTrkProcessors.so'

Clupatra:
  dep: [ROOT, GSL, ILCUTIL, LCIO, RAIDA, Marlin, MarlinUtil, KalTest, MarlinTrk]
  location:
    <<: *ILCUTIL_LOCATION_DEFAULT
  path:
    <<: *CMAKE_PATH_DEFAULT
    lib: '{install}/lib'
    inc: '{install}/include'
    marlin: '{install}/lib/libClupatra.so'

LCFIVertex:
  dep: [ILCUTIL, Marlin, MarlinUtil, LCIO, GEAR, RAIDA]
  location:
    <<: *ILCUTIL_LOCATION_DEFAULT
  path:
    <<: *CMAKE_PATH_DEFAULT
    lib: '{install}/lib'
    inc: '{install}/include'
    marlin: '{install}/lib/libLCFIVertex.so'

LCFIPlus:
  dep: [ILCUTIL, LCIO, GEAR, ROOT, Marlin, MarlinUtil, LCFIVertex]
  location:
    <<: *ILCUTIL_LOCATION_DEFAULT
  path:
    <<: *CMAKE_PATH_DEFAULT
    lib: '{install}/lib'
    inc: '{install}/include'
    marlin: '{install}/lib/libLCFIPlus.so'

KiTrack:
  dep: [ROOT, ILCUTIL, Marlin]
  location:
    <<: *ILCUTIL_LOCATION_DEFAULT
  path:
    <<: *CMAKE_PATH_DEFAULT
    lib: '{install}/lib'
    inc: '{install}/include'

KiTrackMarlin:
  dep: [GSL, CLHEP, ROOT, ILCUTIL, Marlin, MarlinUtil, KiTrack, MarlinTrk]
  location:
    <<: *ILCUTIL_LOCATION_DEFAULT
  path:
    <<: *CMAKE_PATH_DEFAULT
    lib: '{install}/lib'
    inc: '{install}/include'

ForwardTracking:
  dep: [ROOT, GSL, CLHEP, ILCUTIL, LCIO, GEAR, Marlin, MarlinUtil, MarlinTrk, KiTrack, KiTrackMarlin, RAIDA]
  location:
    <<: *ILCUTIL_LOCATION_DEFAULT
  path:
    <<: *CMAKE_PATH_DEFAULT
    lib: '{install}/lib'
    inc: '{install}/include'
    marlin: '{install}/lib/libForwardTracking.so'

MarlinKinfit:
  dep: [GSL, CLHEP, ROOT, ILCUTIL, LCIO, GEAR, Marlin, RAIDA]
  location:
    <<: *ILCUTIL_LOCATION_DEFAULT
  path:
    <<: *CMAKE_PATH_DEFAULT
    lib: '{install}/lib'
    inc: '{install}/include'

PandoraPFANew:
  dep: [ROOT, ILCUTIL]
  location:
    <<: *ILCUTIL_LOCATION_DEFAULT
  path:
    <<: *CMAKE_PATH_DEFAULT
    lib: '{install}/lib'
    inc: '{install}/include'
    library: '{install}/lib'

MarlinPandora:
  dep: [ILCUTIL, Marlin, MarlinUtil, GEAR, PandoraPFANew, LCIO]
  location:
    <<: *ILCUTIL_LOCATION_DEFAULT
  path:
    <<: *CMAKE_PATH_DEFAULT
    inc: '{install}/include'
    lib: '{install}/lib'
    marlin: '{install}/lib/libMarlinPandora.so'

PandoraAnalysis:
  dep: [ROOT, ILCUTIL, Marlin, MarlinUtil, GEAR, LCIO]
  location:
    <<: *ILCUTIL_LOCATION_DEFAULT
  path:
    <<: *CMAKE_PATH_DEFAULT
    bin: '{install}/bin'
    lib: '{install}/lib'
    inc: '{install}/include'
    marlin: '{install}/lib/libPandoraAnalysis.so'

Overlay:
  dep: [ROOT, ILCUTIL, Marlin, MarlinUtil, GEAR, LCIO]
  location:
    <<: *ILCUTIL_LOCATION_DEFAULT
  path:
    <<: *CMAKE_PATH_DEFAULT
    lib: '{install}/lib'
    inc: '{install}/include'
    marlin: '{install}/lib/libOverlay.so'

PathFinder:
  dep: [ROOT, ILCUTIL]
  location:
    <<: *ILCUTIL_LOCATION_DEFAULT
  path:
    <<: *CMAKE_PATH_DEFAULT
    bin: '{install}/bin'
    lib: '{install}/lib'
    inc: '{install}/include'

MarlinTPC:
  dep: [GSL, ROOT, CLHEP, ILCUTIL, LCIO, GEAR, Marlin, LCCD, RAIDA, KalTest, KalDet, Mokka, PathFinder, GBL]
  location:
    <<: *ILCUTIL_LOCATION_DEFAULT
  path:
    <<: *CMAKE_PATH_DEFAULT
    bin: '{install}/bin'
    lib: '{install}/lib'
    inc: '{install}/include'
    marlin: '{install}/lib/libMarlinTPC.so'

LCTuple:
  dep: [ROOT, ILCUTIL, LCIO, Marlin, RAIDA]
  location:
    <<: *ILCUTIL_LOCATION_DEFAULT
  path:
    <<: *CMAKE_PATH_DEFAULT
    lib: '{install}/lib'
    inc: '{install}/include'
    marlin: '{install}/lib/libLCTuple.so'

BBQ:
  dep: [ROOT, ILCUTIL, LCIO, GEAR]
  location:
    <<: *ILCUTIL_LOCATION_DEFAULT
  path:
    <<: *CMAKE_PATH_DEFAULT
    bin: '{install}/bin'
    lib: '{install}/lib'
    inc: '{install}/include'

Garlic:
  dep: [ROOT, ILCUTIL, LCIO, GEAR, Marlin, MarlinUtil]
  location:
    <<: *ILCUTIL_LOCATION_DEFAULT
  path:
    <<: *CMAKE_PATH_DEFAULT
    lib: '{install}/lib'
    inc: '{install}/include'
    marlin: '{install}/lib/libGarlic.so'

HepPDT:
  location:
    <<: *COMMON_LOCATION_DEFAULT
  path:
    <<: *CMAKE_PATH_DEFAULT
    lib: '{install}/lib'
    library: '{install}/lib'
    inc: '{install}/include'

GDML:
  dep: [XercesC, Geant4, ILCUTIL]
  location:
    <<: *ILCUTIL_LOCATION_DEFAULT
  path:
    <<: *CMAKE_PATH_DEFAULT
    lib: '{install}/lib'
    library: '{install}/lib'

LCDD:
  dep: [XercesC, Geant4, ILCUTIL, GDML]
  location:
    <<: *ILCUTIL_LOCATION_DEFAULT
  path:
    <<: *CMAKE_PATH_DEFAULT
    lib: '{install}/lib'
    library: '{install}/lib'
    inc: '{install}/include'
  env:
    GDML_SCHEMA_DIR: '{install}'

SLIC:
  dep: [XercesC, Geant4, ILCUTIL, LCIO, LCDD, GDML, HepPDT]
  location:
    <<: *ILCUTIL_LOCATION_DEFAULT
  path:
    <<: *CMAKE_PATH_DEFAULT
    bin: '{build}/bin'
    inc: '{install}/include'

DD4hep:
  dep: [XercesC, ROOT, Geant4, CLHEP, LCIO, GEAR]
  location:
    <<: *ILCUTIL_LOCATION_DEFAULT
  path:
    <<: *CMAKE_PATH_DEFAULT
    bin: '{install}/bin'
    lib: '{install}/lib'
    library: '{install}/lib'
    inc: '{install}/include'
