Patch:
  install:
    check:
      executable:
        - [patch]
    package_manager:
      yum: patch

Wget:
  install:
    check:
      executable:
        - [wget]
    package_manager:
      yum: wget

Git:
  install: &CHECK_GIT_INSTALL
    check:
      executable:
        - [git]
    package_manager:
      yum: git
  runtime:
    <<: *CHECK_GIT_INSTALL

Subversion:
  install:
    check:
      executable:
        - [svn]
    package_manager:
      yum: subversion

GCCSys:
  install:
    check:
      executable:
        - [gcc]
    package_manager:
      yum: [gcc]

Make:
  install: &CHECK_MAKE_INSTALL
    check:
      executable:
        - [make]
    package_manager:
      yum: make
  runtime:
    <<: *CHECK_MAKE_INSTALL

Java:
  install:
    check:
      executable:
        - [javac]
    package_manager:
      yum: java-1.8.0-openjdk-devel
  runtime:
    check:
      executable:
        - [java]
    package_manager:
      yum: java-1.8.0-openjdk


Python:
  install:
    check:
      include:
        - [python*/Python.h]
    package_manager:
      yum: python-devel
  runtime:
    check:
      executable:
        - [python]
    package_manager:
      yum: python

MySQL:
  install:
    check:
      include:
        - [mysql/mysql.h, mysql.h]
    package_manager:
      yum: mysql-devel
  runtime:
    check:
      executable:
        - [mysql]
    package_manager:
      yum: mysql

SQLite:
  install:
    check:
      include:
        - [sqlite3.h]
    package_manager:
      yum: sqlite-devel
  runtime:
    check:
      executable:
        - [sqlite3]
    package_manager:
      yum: sqlite

OpenSSL:
  install:
    check:
      include:
        - [openssl/ssl.h]
    package_manager:
      yum: openssl-devel
  runtime:
    check:
      executable:
        - [openssl]
    package_manager:
      yum: openssl

#ICU:
#  install:
#    check:
#      include:
#        - [unicode/utypes.h]
#    package_manager:
#      yum: libicu-devel

#PCRE:
#  install:
#    check:
#      include:
#        - [pcre.h]
#    package_manager:
#      yum: pcre-devel

Libxml2:
  install:
    check:
      include:
        - [libxml2/libxml/tree.h, libxml/tree.h]
    package_manager:
      yum: libxml2-devel
  runtime:
    check:
      library:
        - [libxml2.so*]
    package_manager:
      yum: libxml2

#FreeType:
#  install:
#    check:
#      include:
#        - [freetype2/freetype/freetype.h, freetype/freetype.h]
#    package_manager:
#      yum: freetype-devel

FFTW:
  install:
    check:
      include:
        - [fftw3.h]
    package_manager:
      yum: fftw-devel
  runtime:
    check:
      library:
        - [libfftw3.so*]
    package_manager:
      yum: fftw


X11:
  install:
    check:
      include:
        - [X11/Xlib.h]
    package_manager:
      yum: libX11-devel
  runtime:
    check:
      library:
        - [libX11.so*]
    package_manager:
      yum: libX11

Xpm:
  install:
    check:
      include:
        - [X11/xpm.h]
    package_manager:
      yum: libXpm-devel
  runtime:
    check:
      library:
        - [libXpm.so*]
    package_manager:
      yum: libXpm

Xt:
  install:
    check:
      include:
        - [X11/Intrinsic.h]
    package_manager:
      yum: libXt-devel
  runtime:
    check:
      library:
        - [libXt.so*]
    package_manager:
      yum: libXt

Xft:
  install:
    check:
      include:
        - [X11/Xft/Xft.h]
    package_manager:
      yum: libXft-devel
  runtime:
    check:
      library:
        - [libXft.so*]
    package_manager:
      yum: libXft

Xext:
  install:
    check:
      include:
        - [X11/extensions/shape.h]
    package_manager:
      yum: libXext-devel
  runtime:
    check:
      library:
        - [libXext.so*]
    package_manager:
      yum: libXext

Xmu:
  install:
    check:
      include:
        - [X11/Xmu/Xmu.h]
    package_manager:
      yum: libXmu-devel
  runtime:
    check:
      library:
        - [libXmu.so*]
    package_manager:
      yum: libXmu

Xauth:
  install: &CHECK_XAUTH_INSTALL
    check:
      executable:
        - [xauth]
    package_manager:
      yum: xorg-x11-xauth
  runtime:
    <<: *CHECK_XAUTH_INSTALL

OpenGL:
  install:
    check:
      include:
        - [GL/gl.h]
        - [GL/glu.h]
    package_manager:
      yum: [mesa-libGL-devel, mesa-libGLU-devel]
  runtime:
    check:
      library:
        - [libGL.so*]
        - [libGLU.so*]
    package_manager:
      yum: [mesa-libGL, mesa-libGLU]

GLUT:
  install:
    check:
      include:
        - [GL/glut.h]
    package_manager:
      yum: freeglut-devel
  runtime:
    check:
      library:
        - [libglut.so*]
    package_manager:
      yum: freeglut
