GCCSys:
  post_compile:
    handler: lib

Make:
  post_compile:
    handler: lib

MySQL:
  post_compile:
    handler: lib


GCC:
  download:
    handler: http
    param:
      url: http://ftp.gnu.org/gnu/gcc/gcc-{version}/gcc-{version}.tar.gz
  extract:
    handler: tar
    param:
      file: gcc-{version}.tar.gz
      main: gcc-{version}
  pre_compile:
    handler: command
    param:
      cmd: ['contrib/download_prerequisites']
  compile:
    handler: conf_make
    param:
      configure: ['--enable-languages=c,c++,fortran', --disable-multilib]
      install: install-strip
  post_compile:
    handler: lib

CMake:
  download:
    handler: http
    param:
      url: http://www.cmake.org/files/v{version:.3}/cmake-{version}.tar.gz
  extract:
    handler: tar
    param:
      file: cmake-{version}.tar.gz
      main: cmake-{version}
  pre_compile:
    handler: env
  compile:
    handler: conf_make
  post_compile:
    handler: lib


XercesC:
  download:
    handler: http
    param:
      url: https://archive.apache.org/dist/xerces/c/3/sources/xerces-c-{version}.tar.gz
  extract:
    handler: tar
    param:
      file: xerces-c-{version}.tar.gz
      main: xerces-c-{version}
  pre_compile:
    handler: env
  compile:
    handler: conf_make
  post_compile:
    handler: lib

QT:
  download:
    handler: http
    param:
      url: http://download.qt.io/archive/qt/{version:.3}/qt-everywhere-opensource-src-{version}.tar.gz
  extract:
    handler: tar
    param:
      file: qt-everywhere-opensource-src-{version}.tar.gz
      main: qt-everywhere-opensource-src-{version}
  pre_compile:
    handler: env
  compile:
    handler: qt
    param:
      configure: [-prefix-install, -fast, -make, libs, -no-separate-debug-info, -no-xkb, -no-xinerama, -no-webkit, -opensource]
  post_compile:
    handler: lib

CLHEP:
  download:
    handler: http
    param:
      url: https://proj-clhep.web.cern.ch/proj-clhep/DISTRIBUTION/tarFiles/clhep-{version}.tgz
  extract:
    handler: tar
    param:
      file: clhep-{version}.tgz
      main: '{version}/CLHEP'
  pre_compile:
    handler: env
  compile:
    handler: cmake
  post_compile:
    handler: lib

GSL:
  download:
    handler: http
    param:
      url: http://mirrors.kernel.org/gnu/gsl/gsl-{version}.tar.gz
  extract:
    handler: tar
    param:
      file: gsl-{version}.tar.gz
      main: gsl-{version}
  pre_compile:
    handler: env
  compile:
    handler: conf_make
  post_compile:
    handler: lib

ROOT:
  download:
    handler: http
    param:
      url: https://root.cern.ch/download/root_v{version}.source.tar.gz
  extract:
    handler: tar
    param:
      file: root_v{version}.source.tar.gz
      main: root
  pre_compile:
    handler: env
  compile:
    handler: conf_make
    param:
      ignore_install_prefix: true
      configure: 
        - --fail-on-missing
        - --enable-builtin-pcre
        - --enable-explicitlink
        - --enable-soversion
        - --enable-roofit
        - --enable-minuit2
        - --enable-gdml
        - --enable-table
        - --enable-unuran
        - --enable-gsl-shared
        - --with-gsl-incdir={GSL_inc_dir}
        - --with-gsl-libdir={GSL_lib_dir}
        - --enable-qt
        - --with-qt-incdir={QT_inc_dir}
        - --with-qt-libdir={QT_lib_dir}
        - --enable-python
      env_install:
        ROOTSYS: '{ROOT_root_dir}'
  post_compile:
    handler: lib

Geant4:
  download:
    handler: http
    param:
      url: http://geant4.cern.ch/support/source/geant4.{version}.tar.gz
  extract:
    handler: tar
    param:
      file: geant4.{version}.tar.gz
      main: geant4.{version}
  pre_compile:
    handler: env
  compile:
    handler: cmake
    param:
      envcmake:
        GEANT4_INSTALL_DATA: 'ON'
        GEANT4_USE_SYSTEM_EXPAT: 'OFF'
        GEANT4_USE_SYSTEM_CLHEP: 'ON'
        GEANT4_USE_OPENGL_X11: 'ON'
        GEANT4_USE_QT: 'ON'
        GEANT4_USE_GDML: 'ON'
        XERCESC_ROOT_DIR: '{XercesC_root_dir}'
  post_compile:
    handler: lib


ilcsoft_base: &ILCSOFT
  pre_compile:
    handler: env
  compile: &ILCSOFT_COMPILE
    handler: cmake
    param: &ILCSOFT_CMAKE_PARAM
      ignore_install_prefix: true
      envcmake: &ILCSOFT_ENVCMAKE
        BUILD_32BIT_COMPATIBLE: 'OFF'
        INSTALL_DOC: 'OFF'
        CMAKE_BUILD_TYPE: RelWithDebInfo
  post_compile:
    handler: lib


ILCUTIL:
  download:
    handler: svn
    param:
      url: https://svnsrv.desy.de/public/ilctools/ilcutil/tags/v{version}
  pre_compile:
    handler: env
  compile:
    <<: *ILCSOFT_COMPILE


LCIO:
  download:
    handler: svn
    param:
      url: svn://svn.freehep.org/lcio/tags/v{version}
  pre_compile:
    handler: env
  compile:
    handler: cmake
    param:
      ignore_install_prefix: true
      envcmake:
        <<: *ILCSOFT_ENVCMAKE
        BUILD_ROOTDICT: 'ON'
        INSTALL_JAR: 'OFF'

GEAR:
  download:
    handler: svn
    param:
      url: https://svnsrv.desy.de/public/gear/gear/tags/v{version}
  compile:
    handler: cmake
    param:
      ignore_install_prefix: true
      envcmake:
        <<: *ILCSOFT_ENVCMAKE
        GEAR_TGEO: 'ON'

Mokka:
  download:
    handler: svn
    param:
      url: http://llrforge.in2p3.fr/svn/Mokka/tags/mokka-{version}
  compile:
    <<: *ILCSOFT_COMPILE

CondDBMySQL:
  download:
    handler: svn
    param:
      url: https://svnsrv.desy.de/public/calice/CondDBMySQL/tags/CondDBMySQL_ILC-{version}
  compile:
    <<: *ILCSOFT_COMPILE

Druid:
  download:
    handler: svn
    param:
      url: https://svnsrv.desy.de/public/Druid/tags/{version}
  pre_compile:
    handler: env
  compile:
    handler: make
    param:
      make_root: src

CED:
  download:
    handler: svn
    param:
      url: https://svnsrv.desy.de/public/marlinreco/CED/tags/v{version}
  compile:
    handler: cmake
    param:
      ignore_install_prefix: true
      envcmake:
        <<: *ILCSOFT_ENVCMAKE
        CED_SERVER: 'ON'

CEDViewer:
  download:
    handler: svn
    param:
      url: https://svnsrv.desy.de/public/marlinreco/CEDViewer/tags/v{version}
  compile:
    <<: *ILCSOFT_COMPILE

FastJet:
  download:
    handler: http
    param:
      #url: http://www.lpthe.jussieu.fr/~salam/fastjet/repo/fastjet-{version}.tar.gz
      url: http://fastjet.fr/repo/fastjet-{version}.tar.gz
  extract:
    handler: tar
    param:
      file: fastjet-{version}.tar.gz
      main: fastjet-{version}
  pre_compile:
    handler: patch
    param:
      file: fastjet-2.4.2.patch
  compile:
    handler: conf_make
    param:
      configure: --enable-shared

FastJetClustering:
  download:
    handler: svn
    param:
      url: https://svnsrv.desy.de/public/marlinreco/FastJetClustering/tags/v{version}
  compile:
    <<: *ILCSOFT_COMPILE

MarlinFastJet:
  download:
    handler: svn
    param:
      url: https://svnsrv.desy.de/public/marlinreco/MarlinFastJet/tags/v{version}
  compile:
    <<: *ILCSOFT_COMPILE

KalTest:
  download:
    handler: svn
    param:
      url: https://svnsrv.desy.de/public/kaltest/KalTest/tags/v{version}
  compile:
    <<: *ILCSOFT_COMPILE

KalDet:
  download:
    handler: svn
    param:
      url: https://svnsrv.desy.de/public/kaltest/KalDet/tags/v{version}
  compile:
    <<: *ILCSOFT_COMPILE

GBL:
  download:
    handler: svn
    param:
      url: https://svnsrv.desy.de/public/GeneralBrokenLines/tags/V{version}/cpp
  compile:
    <<: *ILCSOFT_COMPILE

LCCD:
  download:
    handler: svn
    param:
      url: https://svnsrv.desy.de/public/lccd/lccd/tags/v{version}
  compile:
    handler: cmake
    param:
      ignore_install_prefix: true
      envcmake:
        <<: *ILCSOFT_ENVCMAKE
        LCCD_CONDDBMYSQL: 'OFF'

RAIDA:
  download:
    handler: svn
    param:
      url: https://svnsrv.desy.de/public/ilctools/RAIDA/tags/v{version}
  compile:
    <<: *ILCSOFT_COMPILE

MarlinUtil:
  download:
    handler: svn
    param:
      url: https://svnsrv.desy.de/public/marlinreco/MarlinUtil/tags/v{version}
  compile:
    <<: *ILCSOFT_COMPILE

Marlin:
  download:
    handler: svn
    param:
      url: https://svnsrv.desy.de/public/marlin/Marlin/tags/v{version}
  compile:
    handler: cmake
    param:
      ignore_install_prefix: true
      envcmake:
        <<: *ILCSOFT_ENVCMAKE
        MARLIN_GUI: 'OFF'

MarlinReco:
  download:
    handler: svn
    param:
      url: https://svnsrv.desy.de/public/marlinreco/MarlinReco/tags/v{version}
  compile:
    handler: cmake
    param:
      ignore_install_prefix: true
      envcmake:
        <<: *ILCSOFT_ENVCMAKE
        MARLINRECO_FORTRAN: 'OFF'

MarlinTrk:
  download:
    handler: svn
    param:
      url: https://svnsrv.desy.de/public/marlinreco/MarlinTrk/tags/v{version}
  compile:
    <<: *ILCSOFT_COMPILE

MarlinTrkProcessors:
  download:
    handler: svn
    param:
      url: https://svnsrv.desy.de/public/marlinreco/MarlinTrkProcessors/tags/v{version}
  compile:
    <<: *ILCSOFT_COMPILE

Clupatra:
  download:
    handler: svn
    param:
      url: https://svnsrv.desy.de/public/marlinreco/Clupatra/tags/v{version}
  compile:
    <<: *ILCSOFT_COMPILE

LCFIVertex:
  pre_compile:
    handler: command
    param:
      cmd: ['tar', '-xvf', 'boost.tgz']
  download:
    handler: svn
    param:
      url: https://svnsrv.desy.de/public/marlinreco/LCFIVertex/tags/v{version}
  compile:
    handler: cmake
    param:
      ignore_install_prefix: true
      envcmake:
        <<: *ILCSOFT_ENVCMAKE
        AIDA: 'OFF'

LCFIPlus:
  download:
    handler: svn
    param:
      url: https://svnsrv.desy.de/public/marlinreco/LCFIPlus/tags/v{version}
  compile:
    <<: *ILCSOFT_COMPILE

KiTrack:
  download:
    handler: svn
    param:
      url: https://svnsrv.desy.de/public/marlinreco/KiTrack/tags/v{version}
  pre_compile:
    handler: patch
    param:
      file: KiTrack-01-04.patch
  compile:
    <<: *ILCSOFT_COMPILE

KiTrackMarlin:
  download:
    handler: svn
    param:
      url: https://svnsrv.desy.de/public/marlinreco/KiTrackMarlin/tags/v{version}
  compile:
    <<: *ILCSOFT_COMPILE

ForwardTracking:
  download:
    handler: svn
    param:
      url: https://svnsrv.desy.de/public/marlinreco/ForwardTracking/tags/v{version}
  compile:
    <<: *ILCSOFT_COMPILE

MarlinKinfit:
  download:
    handler: svn
    param:
      url: https://svnsrv.desy.de/public/marlinreco/MarlinKinfit/tags/v{version}
  compile:
    <<: *ILCSOFT_COMPILE

PandoraPFANew:
  download:
    handler: svn
    param:
      url: https://svnsrv.desy.de/public/PandoraPFANew/PandoraPFANew/tags/v{version}
  compile:
    handler: cmake
    param:
      ignore_install_prefix: true
      envcmake:
        <<: *ILCSOFT_ENVCMAKE
        PANDORA_MONITORING: 'OFF'

MarlinPandora:
  download:
    handler: svn
    param:
      url: https://svnsrv.desy.de/public/PandoraPFANew/MarlinPandora/tags/v{version}
  compile:
    handler: cmake
    param:
      ignore_install_prefix: true
      envcmake:
        <<: *ILCSOFT_ENVCMAKE
        PANDORA_MONITORING: 'OFF'

PandoraAnalysis:
  download:
    handler: svn
    param:
      url: https://svnsrv.desy.de/public/PandoraPFANew/PandoraAnalysis/tags/v{version}
  compile:
    <<: *ILCSOFT_COMPILE

Overlay:
  download:
    handler: svn
    param:
      url: https://svnsrv.desy.de/public/marlin/Overlay/tags/v{version}
  compile:
    <<: *ILCSOFT_COMPILE

PathFinder:
  download:
    handler: svn
    param:
      url: https://svnsrv.desy.de/public/pathfinder/tags/v{version}
  compile:
    <<: *ILCSOFT_COMPILE

MarlinTPC:
  download:
    handler: svn
    param:
      url: https://svnsrv.desy.de/public/marlintpc/tags/v{version}
  compile:
    <<: *ILCSOFT_COMPILE

LCTuple:
  download:
    handler: svn
    param:
      url: https://svnsrv.desy.de/public/marlinreco/LCTuple/tags/v{version}
  compile:
    <<: *ILCSOFT_COMPILE

BBQ:
  download:
    handler: svn
    param:
      url: https://svnsrv.desy.de/public/bbq/tags/v{version}
  compile:
    <<: *ILCSOFT_COMPILE

Garlic:
  download:
    handler: svn
    param:
      url: https://svnsrv.desy.de/public/Garlic/tags/v{version}
  compile:
    <<: *ILCSOFT_COMPILE

HepPDT:
  download:
    handler: http
    param:
      url: http://lcgapp.cern.ch/project/simu/HepPDT/download/HepPDT-{version}.tar.gz
  extract:
    handler: tar
    param:
      file: HepPDT-{version}.tar.gz
      main: HepPDT-{version}
  compile:
    handler: conf_make

GDML:
  download:
    handler: svn
    param:
      url: svn://svn.freehep.org/lcdet/projects/gdml/tags/v{version}
  compile:
    <<: *ILCSOFT_COMPILE

LCDD:
  download:
    handler: svn
    param:
      url: svn://svn.freehep.org/lcdet/projects/lcdd/tags/v{version}
  compile:
    <<: *ILCSOFT_COMPILE

SLIC:
  download:
    handler: svn
    param:
      url: svn://svn.freehep.org/lcdet/projects/slic/tags/v{version}
  compile:
    handler: cmake
    param:
      <<: *ILCSOFT_CMAKE_PARAM
      do_make_install: false

DD4hep:
  download:
    handler: svn
    param:
      url: https://svnsrv.desy.de/public/aidasoft/DD4hep/tags/v{version}
  compile:
    handler: cmake
    param:
      ignore_install_prefix: true
      envcmake:
        <<: *ILCSOFT_ENVCMAKE
        DD4HEP_WITH_GEANT4: '0'
        DD4HEP_USE_XERCESC: '0'
        DD4HEP_USE_PYROOT: '0'
