gcc:
  version: 4.9.4
  category: external
  path: Service

CMake:
  version: 2.8.5
  category: external
  path: Service


MySQL:
  category: system


XercesC:
  version: 3.2.0
  category: external
  path: Service

GSL:
  version: '1.14'
  category: external
  path: Service

QT:
  version: 4.7.4
  category: external
  path: Service

ROOT:
  version: 5.34.10
  category: external
  path: Service

CLHEP:
  version: 2.1.3.1
  category: external
  path: Service

Geant4:
  version: 9.6.p02
  category: external
  path: Service


ILCUTIL:
  version: 01-01
  category: cepcsoft
  path: Framework

LCIO:
  version: 02-04-03
  category: cepcsoft
  path: Framework


GEAR:
  version: 01-04
  category: cepcsoft
  path: Simulation

Mokka:
  version: 08-03
  category: cepcsoft
  path: Simulation


Druid:
  version: '2.2'
  category: cepcsoft
  path: EventDisplay

#CED:
#  version: 01-09-01
#  category: cepcsoft
#  path: EventDisplay
#
#CEDViewer:
#  version: 01-07-02
#  category: cepcsoft
#  path: EventDisplay
#
#
#LCCD:
#  version: 01-03
#  category: cepcsoft
#  path: Simulation
#
#NNNN:
#  version: 
#  category: cepcsoft
#  path: kkkk
