cepcenv:
  require: {'>=': '0.2', '<': '0.3'}

category:
  priority: [work, cepcsoft, external, standby]
  extra_config: [work_root]
  categories:
    not_used: {}
    system:
      pre_check: true
    external:
      install: true
      auto_env: true
      required_config: [software_root, platform]
      root: '{software_root}/{platform}/external'
    cepcsoft:
      install: true
      auto_env: true
      required_config: [software_root, platform]
      root: '{software_root}/{platform}/cepcsoft/{version}'
    work:
      auto_package: true
      auto_env: true
      required_config: [work_root]
      root: '{work_root}'
    standby:
      auto_package: true
      auto_env: false
      required_config: [software_root, platform]
      root: '{software_root}/{platform}/standby'

global_env:
  CEPCSOFT: '{software_root}/{platform}/cepcsoft/{version}'
  CEPCSOFT_EXTERNAL: '{software_root}/{platform}/external'
  CEPCSOFT_VERSION: '{version}'

path_usage:
  install:
    home: '{package}_root_dir'
    bin: '{package}_bin_dir'
    src: '{package}_src_dir'
    lib: '{package}_lib_dir'
    inc: '{package}_inc_dir'
  multi_env:
    bin: PATH
    lib: LD_LIBRARY_PATH
    man: MANPATH
    info: INFOPATH
    pkgconfig: PKG_CONFIG_PATH
    cmake: CMAKE_PREFIX_PATH
    marlin: MARLIN_DLL
  single_env:
    home: '{package}_HOME'
    src: '{package}_SOURCE'
    bin: '{package}_BIN'
    lib: '{package}_LIB'
    inc: '{package}_INCLUDE'

handler:
  auto_compile: auto_cmake

pre_transform: [basic_package, gcc_version, geant4_libdir]
